# Generated by Django 5.0.6 on 2024-05-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_siteconfiguration_contact_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='contact_text',
            field=models.TextField(default=''),
        ),
    ]
